services:
  sllaunes: # Aplicació
    image: illaunes:1.0
    build: .
    expose:
      - "80"
    environment:
      - HOST_NAME=pj9af4
    networks:
      - pj9f5

  sDc: # Distribuidor de carrega
    image: Nginx:latest
    container_name: cNginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sllaunes
    ports:
      - "80:8000"
    networks:
      - pj9f5

networks:
  pj9f5:
    name: xPj9f5
    driver: bridge